### ISSUE TITLE
python module `six` is required

### ISSUE THREAD

**Issue by mbrannigan** [Inveracity/jinjabread#2]
I built the docker image and got the following error message at runtime:
```
[Sat Oct 01 05:28:45.220708 2016] [wsgi:error] [pid 9:tid 140577801398016] [client 172.17.0.1:36968] ImportError: No module named six
```

Doing a `pip install six` inside of the running container fixed things.

Here's a patch.  If you'd like, I could do a PR.
```
diff --git a/Dockerfile b/Dockerfile
index ea7d0b3..8604c19 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -9,6 +9,7 @@ RUN apt-get -y install python-pip
 RUN pip install --upgrade pip
 RUN pip install Flask
 RUN pip install pyyaml
+RUN pip install six
 RUN apt-get -y install apache2
 RUN apt-get -y install libapache2-mod-wsgi
 RUN apt-get -y install python-dev
```

Thanks for this project!  It's going to help me out a lot.

**Comment by Inveracity** [comment]
Thank you for reporting!
I didn't realise I was importing from `pythonpath` here at my own computer, I actually wanted to use the six module I copied from Saltstack.
This commit should take care of the dependency without needing to install six https://github.com/Inveracity/jinjabread/commit/ad2eded001bf3cd8c8cd88b0aade4152296e78f1

But it's not pretty, so I may make six a dependency down the line.. hm.

Also, feel free to post any missing features, it's lacking in a lot of saltstack specific features at the moment, so when you come across them, I'd love to know about it!

I hope the tool comes in handy!

**Comment by mbrannigan** [comment]
Awesome.  Works great!  Thanks again.
